### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by enoch85** [techandme/nextcloud-packer#1]
- [ ] Chown to daniel:daniel or (user:user)
- [ ] Set output folder
- [ ] Figure out how to get a real shell instead of a non interactive / no Dialog
- [ ] Run the install script as ncadmin not root
- [ ] Can we ues RAR instead of ZIP?
- [ ] Intcrease compression level to 9
- [ ] Make larger builds (new json files)
- [ ] Create a setup script for first time install (Packer, Vagrant, Ruby and stuff)
- [ ] Hostname does not apply from preseed.cfg
- [ ] Setting GRUB_TIMEOUT to HIDDEN_TIMEOUT is no longer supported
- [ ] Remove the [ IFACE ] && in the startup script? (It errors the first try)
